// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZfncFHkmQsOSdQ26Jr1yzJDTSOwr8WA',
    appId: '1:756414699752:web:87b5234300f4db89e8115d',
    messagingSenderId: '756414699752',
    projectId: 'parkyou-ffa9d',
    authDomain: 'parkyou-ffa9d.firebaseapp.com',
    storageBucket: 'parkyou-ffa9d.appspot.com',
    measurementId: 'G-MNJNS362FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMCDLnR8QHLUr7rj9aAPf63IG5WdO_4s',
    appId: '1:756414699752:android:6d1176b07549df72e8115d',
    messagingSenderId: '756414699752',
    projectId: 'parkyou-ffa9d',
    storageBucket: 'parkyou-ffa9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPO6gi42KK2-NLu6X0KH1DZ9vHAGlHbUs',
    appId: '1:756414699752:ios:22842f0d032893c0e8115d',
    messagingSenderId: '756414699752',
    projectId: 'parkyou-ffa9d',
    storageBucket: 'parkyou-ffa9d.appspot.com',
    iosClientId: '756414699752-skqkl88c3rfcrl89n8bpesbqmus95ou0.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPO6gi42KK2-NLu6X0KH1DZ9vHAGlHbUs',
    appId: '1:756414699752:ios:22842f0d032893c0e8115d',
    messagingSenderId: '756414699752',
    projectId: 'parkyou-ffa9d',
    storageBucket: 'parkyou-ffa9d.appspot.com',
    iosClientId: '756414699752-skqkl88c3rfcrl89n8bpesbqmus95ou0.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkyou',
  );
}
